import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, test, vi } from "vitest";
import { defineSchema, id, text } from "../../../database/schema-builder";
import { generateDatabaseTypes, SCHEMA_REL } from "../generator";

const fakeSchema = defineSchema(({ table }) => ({
  user: table("user", {
    id: id(),
    email: text().notNull(),
  }),
}));

async function mkApp(source: string): Promise<{
  projectRoot: string;
  outFile: string;
  columnsOutFile: string;
  cleanup: () => Promise<void>;
}> {
  const projectRoot = await fs.mkdtemp(
    path.join(os.tmpdir(), "appkit-typegen-"),
  );
  const schemaPath = path.join(projectRoot, SCHEMA_REL);
  await fs.mkdir(path.dirname(schemaPath), { recursive: true });
  await fs.writeFile(schemaPath, source, "utf8");
  const outFile = path.join(projectRoot, "shared/appkit-types/database.d.ts");
  const columnsOutFile = path.join(
    projectRoot,
    "shared/appkit-types/database.columns.ts",
  );
  return {
    projectRoot,
    outFile,
    columnsOutFile,
    cleanup: () => fs.rm(projectRoot, { recursive: true, force: true }),
  };
}

let pendingCleanups: Array<() => Promise<void>> = [];
afterEach(async () => {
  for (const fn of pendingCleanups) await fn();
  pendingCleanups = [];
});

async function track(
  result: Awaited<ReturnType<typeof mkApp>>,
): Promise<typeof result> {
  pendingCleanups.push(result.cleanup);
  return result;
}

describe("generateDatabaseTypes — output", () => {
  test("skips silently when schema.ts is missing", async () => {
    const projectRoot = await fs.mkdtemp(
      path.join(os.tmpdir(), "appkit-typegen-empty-"),
    );
    pendingCleanups.push(() =>
      fs.rm(projectRoot, { recursive: true, force: true }),
    );
    const outFile = path.join(projectRoot, "shared/appkit-types/database.d.ts");

    await expect(
      generateDatabaseTypes({
        outFile,
        projectRoot,
        loadModule: () => Promise.reject(new Error("should not be called")),
        noCache: true,
      }),
    ).resolves.toBeUndefined();

    await expect(fs.access(outFile)).rejects.toThrow();
  });

  test("writes a registry-augmenting .d.ts for the injected schema", async () => {
    const app = await track(await mkApp("// fake schema source\n"));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: async () => ({ default: fakeSchema }),
      noCache: true,
    });

    const content = await fs.readFile(app.outFile, "utf8");
    const columns = await fs.readFile(app.columnsOutFile, "utf8");
    expect(content).toContain("Auto-generated by AppKit");
    expect(content).toContain('declare module "@databricks/appkit-ui/js"');
    expect(content).toContain("interface DatabaseRegistry");
    expect(content).toContain("user: {");
    expect(content).toContain("row: { id: number; email: string; };");
    expect(content).toContain("insert: { id?: number; email: string; };");
    expect(content).toContain("update: { id?: number; email?: string; };");
    expect(content).toContain("includes: {};");
    expect(columns).toContain("export const databaseColumns");
    expect(columns).toContain("registerDatabaseColumns(databaseColumns)");
    expect(columns).toContain("user: [");
    expect(columns).toContain('name: "id"');
    expect(columns).toContain("primaryKey: true");
  });

  test("generated database.columns.ts only imports symbols actually exported from @databricks/appkit-ui/js", async () => {
    // Regression: a typo in the emitted import name parses fine but throws on
    // first page load. Assert every imported binding exists in the barrel.
    const app = await track(await mkApp("// fake schema source\n"));
    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: async () => ({ default: fakeSchema }),
      noCache: true,
    });

    const generated = await fs.readFile(app.columnsOutFile, "utf8");
    const importedNames = Array.from(
      generated.matchAll(
        /^import\s*(?:type\s*)?{([^}]+)}\s*from\s*"@databricks\/appkit-ui\/js";$/gm,
      ),
    ).flatMap((m) =>
      (m[1] ?? "")
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    );
    expect(importedNames.length).toBeGreaterThan(0);

    const barrel = await fs.readFile(
      path.resolve(
        __dirname,
        "../../../../../appkit-ui/src/js/database/index.ts",
      ),
      "utf8",
    );
    for (const name of importedNames) {
      const re = new RegExp(`\\b${name}\\b`);
      expect(barrel).toMatch(re);
    }
  });

  test("emits an empty module when the schema has no tables", async () => {
    const app = await track(await mkApp("// empty\n"));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: async () => ({ default: { $tables: {} } }),
      noCache: true,
    });

    const content = await fs.readFile(app.outFile, "utf8");
    const columns = await fs.readFile(app.columnsOutFile, "utf8");
    expect(content).toContain("export {};");
    expect(content).not.toContain("declare module");
    expect(columns).toContain(
      "export const databaseColumns: Record<string, readonly ColumnInfo[]> = {};",
    );
    expect(columns).toContain("registerDatabaseColumns(databaseColumns)");
  });

  test("throws when the module has no default export", async () => {
    const app = await track(await mkApp("// fake\n"));

    await expect(
      generateDatabaseTypes({
        outFile: app.outFile,
        projectRoot: app.projectRoot,
        loadModule: async () => ({}) as never,
        noCache: true,
      }),
    ).rejects.toThrow(/no default export/);
  });
});

describe("generateDatabaseTypes — cache", () => {
  test("reuses cached output on matching source hash", async () => {
    const app = await track(await mkApp("// v1\n"));
    const loader = vi.fn(async () => ({ default: fakeSchema }));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });
    const first = await fs.readFile(app.outFile, "utf8");

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });
    const second = await fs.readFile(app.outFile, "utf8");

    expect(loader).toHaveBeenCalledTimes(1);
    expect(second).toBe(first);
  });

  test("invalidates when the source hash changes", async () => {
    const app = await track(await mkApp("// v1\n"));
    const loader = vi.fn(async () => ({ default: fakeSchema }));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });

    await fs.writeFile(
      path.join(app.projectRoot, SCHEMA_REL),
      "// v2\n",
      "utf8",
    );

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });

    expect(loader).toHaveBeenCalledTimes(2);
  });

  test("noCache forces the loader to run even on matching hashes", async () => {
    const app = await track(await mkApp("// v1\n"));
    const loader = vi.fn(async () => ({ default: fakeSchema }));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
      noCache: true,
    });
    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
      noCache: true,
    });

    expect(loader).toHaveBeenCalledTimes(2);
  });

  test("invalidates when a relative import target changes", async () => {
    // Split-schema setup: editing an imported table file must bust the cache.
    const app = await track(
      await mkApp(
        `import { user } from "./tables/user";\nexport default user;\n`,
      ),
    );
    const tablesDir = path.join(app.projectRoot, "config/database/tables");
    const userTable = path.join(tablesDir, "user.ts");
    await fs.mkdir(tablesDir, { recursive: true });
    await fs.writeFile(userTable, "export const user = 'v1';\n", "utf8");

    const loader = vi.fn(async () => ({ default: fakeSchema }));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });

    await fs.writeFile(userTable, "export const user = 'v2';\n", "utf8");

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });

    expect(loader).toHaveBeenCalledTimes(2);
  });
});
