import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, test, vi } from "vitest";
import { defineSchema, id, text } from "../../../database/schema-builder";
import { generateDatabaseTypes, SCHEMA_REL } from "../generator";

const fakeSchema = defineSchema(({ table }) => ({
  user: table("user", {
    id: id(),
    email: text().notNull(),
  }),
}));

async function mkApp(
  source: string,
): Promise<{
  projectRoot: string;
  outFile: string;
  cleanup: () => Promise<void>;
}> {
  const projectRoot = await fs.mkdtemp(
    path.join(os.tmpdir(), "appkit-typegen-"),
  );
  const schemaPath = path.join(projectRoot, SCHEMA_REL);
  await fs.mkdir(path.dirname(schemaPath), { recursive: true });
  await fs.writeFile(schemaPath, source, "utf8");
  const outFile = path.join(projectRoot, "shared/appkit-types/database.d.ts");
  return {
    projectRoot,
    outFile,
    cleanup: () => fs.rm(projectRoot, { recursive: true, force: true }),
  };
}

let pendingCleanups: Array<() => Promise<void>> = [];
afterEach(async () => {
  for (const fn of pendingCleanups) await fn();
  pendingCleanups = [];
});

async function track(
  result: Awaited<ReturnType<typeof mkApp>>,
): Promise<typeof result> {
  pendingCleanups.push(result.cleanup);
  return result;
}

describe("generateDatabaseTypes — output", () => {
  test("skips silently when schema.ts is missing", async () => {
    const projectRoot = await fs.mkdtemp(
      path.join(os.tmpdir(), "appkit-typegen-empty-"),
    );
    pendingCleanups.push(() =>
      fs.rm(projectRoot, { recursive: true, force: true }),
    );
    const outFile = path.join(projectRoot, "shared/appkit-types/database.d.ts");

    await expect(
      generateDatabaseTypes({
        outFile,
        projectRoot,
        loadModule: () => Promise.reject(new Error("should not be called")),
        noCache: true,
      }),
    ).resolves.toBeUndefined();

    await expect(fs.access(outFile)).rejects.toThrow();
  });

  test("writes a registry-augmenting .d.ts for the injected schema", async () => {
    const app = await track(await mkApp("// fake schema source\n"));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: async () => ({ default: fakeSchema }),
      noCache: true,
    });

    const content = await fs.readFile(app.outFile, "utf8");
    expect(content).toContain("Auto-generated by AppKit");
    expect(content).toContain('declare module "@databricks/appkit-ui/js"');
    expect(content).toContain("interface DatabaseRegistry");
    expect(content).toContain("user: {");
    expect(content).toContain("row: { id: number; email: string; };");
    expect(content).toContain("insert: { id?: number; email: string; };");
    expect(content).toContain("update: { id?: number; email?: string; };");
    expect(content).toContain("includes: {};");
  });

  test("emits an empty module when the schema has no tables", async () => {
    const app = await track(await mkApp("// empty\n"));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: async () => ({ default: { $tables: {} } }),
      noCache: true,
    });

    const content = await fs.readFile(app.outFile, "utf8");
    expect(content).toContain("export {};");
    expect(content).not.toContain("declare module");
  });

  test("throws when the module has no default export", async () => {
    const app = await track(await mkApp("// fake\n"));

    await expect(
      generateDatabaseTypes({
        outFile: app.outFile,
        projectRoot: app.projectRoot,
        loadModule: async () => ({}) as never,
        noCache: true,
      }),
    ).rejects.toThrow(/no default export/);
  });
});

describe("generateDatabaseTypes — cache", () => {
  test("reuses cached output on matching source hash", async () => {
    const app = await track(await mkApp("// v1\n"));
    const loader = vi.fn(async () => ({ default: fakeSchema }));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });
    const first = await fs.readFile(app.outFile, "utf8");

    // Second run with identical source should hit the cache and skip the loader.
    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });
    const second = await fs.readFile(app.outFile, "utf8");

    expect(loader).toHaveBeenCalledTimes(1);
    expect(second).toBe(first);
  });

  test("invalidates when the source hash changes", async () => {
    const app = await track(await mkApp("// v1\n"));
    const loader = vi.fn(async () => ({ default: fakeSchema }));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });

    // Bump the schema source — cache should miss and the loader should run again.
    await fs.writeFile(
      path.join(app.projectRoot, SCHEMA_REL),
      "// v2\n",
      "utf8",
    );

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
    });

    expect(loader).toHaveBeenCalledTimes(2);
  });

  test("noCache forces the loader to run even on matching hashes", async () => {
    const app = await track(await mkApp("// v1\n"));
    const loader = vi.fn(async () => ({ default: fakeSchema }));

    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
      noCache: true,
    });
    await generateDatabaseTypes({
      outFile: app.outFile,
      projectRoot: app.projectRoot,
      loadModule: loader,
      noCache: true,
    });

    expect(loader).toHaveBeenCalledTimes(2);
  });
});
