import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { Command } from "commander";
import { execa } from "execa";
import {
  bullet,
  check,
  databasePaths,
  drizzleKitBinPath,
  loadSchemaFile,
  runCommandAction,
} from "./shared";

export interface GenerateMigrationOptions {
  name?: string;
}

export async function generateMigration(
  options: GenerateMigrationOptions = {},
): Promise<void> {
  const paths = databasePaths();
  const drizzleSchemaFile = await writeDrizzleSchemaProxy();
  const args = [
    "drizzle-kit",
    "generate",
    "--out",
    path.relative(paths.root, paths.migrationsDir),
    "--schema",
    path.relative(paths.root, drizzleSchemaFile),
    "--dialect",
    "postgresql",
  ];
  if (options.name) args.push("--name", options.name);

  console.log(bullet(`drizzle-kit ${args.slice(1).join(" ")}`));
  await execa(process.execPath, [drizzleKitBinPath(), ...args.slice(1)], {
    cwd: paths.root,
    stdio: "inherit",
    env: process.env,
  });
  console.log(check("Migration generated under config/database/migrations."));
}

async function writeDrizzleSchemaProxy(): Promise<string> {
  const paths = databasePaths();
  const schema = await loadSchemaFile(paths.schemaFile);
  if (!schema) {
    throw new Error("config/database/schema.ts not found.");
  }

  const tables =
    (schema as { $tables?: Record<string, unknown> }).$tables ?? {};
  const tableNames = Object.keys(tables);
  if (tableNames.length === 0) {
    throw new Error("config/database/schema.ts does not define any tables.");
  }

  const generatedDir = path.join(
    paths.root,
    "node_modules/.databricks/appkit/database",
  );
  const generatedFile = path.join(generatedDir, "drizzle-schema.mjs");
  await mkdir(generatedDir, { recursive: true });
  await writeFile(
    generatedFile,
    [
      "// AUTO-GENERATED by AppKit. Do not edit.",
      `import appkitSchema from ${JSON.stringify(pathToFileURL(paths.schemaFile).href)};`,
      "",
      ...tableNames.map(
        (name) =>
          `export const ${toSafeIdentifier(name)} = appkitSchema.$tables[${JSON.stringify(name)}].$drizzle;`,
      ),
      "",
    ].join("\n"),
    "utf8",
  );
  return generatedFile;
}

function toSafeIdentifier(value: string): string {
  const normalized = value.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[a-zA-Z_$]/.test(normalized) ? normalized : `table_${normalized}`;
}

export const migrationCommand = new Command("migration")
  .description(
    "Generate database migration files from config/database/schema.ts",
  )
  .addCommand(
    new Command("generate")
      .description("Generate the next migration from config/database/schema.ts")
      .option("--name <name>", "Optional migration name")
      .action((opts) =>
        runCommandAction(() =>
          generateMigration({
            name: opts.name ? String(opts.name) : undefined,
          }),
        ),
      ),
  );
