// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    app_activity_heatmap: {
        name: "app_activity_heatmap";
        parameters: {
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType STRING */
          day_of_week: string;
          /** @sqlType DECIMAL(35,2) */
          spend: number;
        }>;
      };
    apps_list: {
        name: "apps_list";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          creator: string;
          /** @sqlType STRING */
          tags: string;
          /** @sqlType DECIMAL(38,6) */
          totalSpend: number;
          /** @sqlType DATE */
          createdAt: string;
        }>;
      };
    cost_recommendations: {
        name: "cost_recommendations";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType INT */
          dummy: number;
        }>;
      };
    dashboard_fare_distribution: {
        name: "dashboard_fare_distribution";
        parameters: {
          /** STRING - use sql.string() */
          dateFrom: SQLStringMarker;
          /** STRING - use sql.string() */
          dateTo: SQLStringMarker;
          /** STRING - use sql.string() */
          pickupZip: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          fare_bucket: string;
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          avg_distance: number;
        }>;
      };
    dashboard_hourly_heatmap: {
        name: "dashboard_hourly_heatmap";
        parameters: {
          /** STRING - use sql.string() */
          dateFrom: SQLStringMarker;
          /** STRING - use sql.string() */
          dateTo: SQLStringMarker;
          /** STRING - use sql.string() */
          pickupZip: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMin: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMax: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          day_of_week: number;
          /** @sqlType INT */
          hour_of_day: number;
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          avg_fare: number;
        }>;
      };
    dashboard_kpi_sparklines: {
        name: "dashboard_kpi_sparklines";
        parameters: {
          /** STRING - use sql.string() */
          dateFrom: SQLStringMarker;
          /** STRING - use sql.string() */
          dateTo: SQLStringMarker;
          /** STRING - use sql.string() */
          pickupZip: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMin: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMax: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          trip_date: string;
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          total_revenue: number;
          /** @sqlType DOUBLE */
          avg_fare: number;
          /** @sqlType DOUBLE */
          avg_distance: number;
        }>;
      };
    dashboard_kpis: {
        name: "dashboard_kpis";
        parameters: {
          /** STRING - use sql.string() */
          dateFrom: SQLStringMarker;
          /** STRING - use sql.string() */
          dateTo: SQLStringMarker;
          /** STRING - use sql.string() */
          pickupZip: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMin: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMax: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          total_trips: number;
          /** @sqlType DOUBLE */
          avg_fare: number;
          /** @sqlType DOUBLE */
          avg_distance: number;
          /** @sqlType DOUBLE */
          max_fare: number;
          /** @sqlType DOUBLE */
          min_fare: number;
        }>;
      };
    dashboard_top_zone: {
        name: "dashboard_top_zone";
        parameters: {
          /** STRING - use sql.string() */
          dateFrom: SQLStringMarker;
          /** STRING - use sql.string() */
          dateTo: SQLStringMarker;
          /** STRING - use sql.string() */
          pickupZip: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMin: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMax: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          pickup_zip: number;
          /** @sqlType BIGINT */
          trip_count: number;
        }>;
      };
    dashboard_top_zones: {
        name: "dashboard_top_zones";
        parameters: {
          /** STRING - use sql.string() */
          dateFrom: SQLStringMarker;
          /** STRING - use sql.string() */
          dateTo: SQLStringMarker;
          /** STRING - use sql.string() */
          pickupZip: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMin: SQLStringMarker;
          /** STRING - use sql.string() */
          fareMax: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          pickup_zip: string;
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          total_revenue: number;
          /** @sqlType DOUBLE */
          avg_fare: number;
        }>;
      };
    dashboard_trips_over_time: {
        name: "dashboard_trips_over_time";
        parameters: {
          /** STRING - use sql.string() */
          dateFrom: SQLStringMarker;
          /** STRING - use sql.string() */
          dateTo: SQLStringMarker;
          /** STRING - use sql.string() */
          pickupZip: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          trip_date: string;
          /** @sqlType BIGINT */
          trip_count: number;
          /** @sqlType DOUBLE */
          avg_fare: number;
          /** @sqlType DOUBLE */
          total_revenue: number;
        }>;
      };
    example: {
        name: "example";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BOOLEAN */
          "(1 = 1)": boolean;
        }>;
      };
    spend_data: {
        name: "spend_data";
        parameters: {
          /** STRING - use sql.string() */
          groupBy: SQLStringMarker;
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
          /** STRING - use sql.string() */
          appId: SQLStringMarker;
          /** STRING - use sql.string() */
          creator: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          group_key: string;
          /** @sqlType TIMESTAMP */
          aggregation_period: string;
          /** @sqlType DECIMAL(38,6) */
          cost_usd: number;
        }>;
      };
    spend_summary: {
        name: "spend_summary";
        parameters: {
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType DECIMAL(33,0) */
          total: number;
          /** @sqlType DECIMAL(33,0) */
          average: number;
          /** @sqlType DECIMAL(33,0) */
          forecasted: number;
        }>;
      };
    sql_helpers_test: {
        name: "sql_helpers_test";
        parameters: {
          /** STRING - use sql.string() */
          stringParam: SQLStringMarker;
          /** NUMERIC - use sql.number() */
          numberParam: SQLNumberMarker;
          /** BOOLEAN - use sql.boolean() */
          booleanParam: SQLBooleanMarker;
          /** DATE - use sql.date() */
          dateParam: SQLDateMarker;
          /** TIMESTAMP - use sql.timestamp() */
          timestampParam: SQLTimestampMarker;
          /** STRING - use sql.string() */
          binaryParam: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          string_value: string;
          /** @sqlType INT */
          number_value: number;
          /** @sqlType BOOLEAN */
          boolean_value: boolean;
          /** @sqlType STRING */
          date_value: string;
          /** @sqlType STRING */
          timestamp_value: string;
          /** @sqlType BINARY */
          binary_value: string;
          /** @sqlType STRING */
          binary_hex: string;
          /** @sqlType INT */
          binary_length: number;
        }>;
      };
    top_contributors: {
        name: "top_contributors";
        parameters: {
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType DECIMAL(38,6) */
          total_cost_usd: number;
        }>;
      };
    untagged_apps: {
        name: "untagged_apps";
        parameters: {
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType STRING */
          creator: string;
          /** @sqlType DECIMAL(38,6) */
          total_cost_usd: number;
          /** @sqlType DECIMAL(38,10) */
          avg_period_cost_usd: number;
        }>;
      };
  }
}
