import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import pc from "picocolors";
import { createLogger } from "../../logging/logger";
import {
  CACHE_VERSION,
  type DatabaseCache,
  hashSchemaSourceWithDeps,
  loadDatabaseCache,
  saveDatabaseCache,
} from "./cache";
import { type RegistryEntry, walkSchema } from "./walk-schema";

const logger = createLogger("type-generator:database");

/** User's declarative schema file, relative to the project root. */
export const SCHEMA_REL = "config/database/schema.ts";
export const DATABASE_TYPES_FILE = "shared/appkit-types/database.d.ts";
export const DATABASE_COLUMNS_FILE = "shared/appkit-types/database.columns.ts";

/** Vite passes `ssrLoadModule`; CLI/tests use plain `import()`. */
export type SchemaLoader = (
  schemaPath: string,
) => Promise<{ default: unknown }>;

const defaultLoader: SchemaLoader = (schemaPath) =>
  import(pathToFileURL(schemaPath).href) as Promise<{ default: unknown }>;

export interface GenerateDatabaseTypesOptions {
  /** Absolute path to the `.d.ts` output. */
  outFile: string;
  /** Absolute path to the runtime columns module. */
  columnsOutFile?: string;
  /** Directory containing `config/database/schema.ts`. */
  projectRoot: string;
  loadModule?: SchemaLoader;
  /** Bypass the on-disk hash cache. */
  noCache?: boolean;
}

/**
 * Walk `schema.ts` and emit `database.d.ts` + `database.columns.ts`.
 * No-op when `schema.ts` is missing.
 */
export async function generateDatabaseTypes(
  options: GenerateDatabaseTypesOptions,
): Promise<void> {
  const schemaPath = path.join(options.projectRoot, SCHEMA_REL);
  const columnsOutFile =
    options.columnsOutFile ??
    path.join(options.projectRoot, DATABASE_COLUMNS_FILE);
  const loadModule = options.loadModule ?? defaultLoader;
  const start = performance.now();

  try {
    await fs.access(schemaPath);
  } catch {
    logger.debug(
      "No schema.ts at %s; skipping database type generation",
      schemaPath,
    );
    return;
  }

  // Hash the full import graph so split-schema setups (`./tables/*.ts`)
  // invalidate when an imported file changes.
  const hash = await hashSchemaSourceWithDeps(schemaPath);
  const cache = options.noCache
    ? { version: CACHE_VERSION }
    : await loadDatabaseCache(options.projectRoot);

  if (
    !options.noCache &&
    cache.entry?.hash === hash &&
    cache.entry.columnsOutput
  ) {
    await writeOutput(options.outFile, cache.entry.output);
    await writeOutput(columnsOutFile, cache.entry.columnsOutput);
    printLog("HIT", start, []);
    return;
  }

  const mod = await loadModule(schemaPath);
  if (!mod || typeof mod !== "object" || !("default" in mod)) {
    throw new Error(
      `schema.ts at ${schemaPath} has no default export. Use 'export default defineSchema(...)'.`,
    );
  }

  const entries = walkSchema(mod.default);
  const output = renderDeclaration(entries);
  const columnsOutput = renderColumnsModule(entries);
  await writeOutput(options.outFile, output);
  await writeOutput(columnsOutFile, columnsOutput);

  if (!options.noCache) {
    const next: DatabaseCache = {
      version: CACHE_VERSION,
      entry: { hash, output, columnsOutput },
    };
    await saveDatabaseCache(options.projectRoot, next);
  }

  printLog("MISS", start, entries);
}

function renderColumnsModule(entries: RegistryEntry[]): string {
  // Side-effect import populates the column registry so `db.<entity>.columns()`
  // skips the HTTP round-trip. Auto-injected by the Vite plugin.
  const header = [
    "// Auto-generated by AppKit — DO NOT EDIT",
    "// Generated from config/database/schema.ts",
    "",
    'import type { ColumnInfo } from "@databricks/appkit-ui/js";',
    'import { registerDatabaseColumns } from "@databricks/appkit-ui/js";',
    "",
  ].join("\n");

  if (entries.length === 0) {
    return [
      header,
      "export const databaseColumns: Record<string, readonly ColumnInfo[]> = {};",
      "",
      "registerDatabaseColumns(databaseColumns);",
      "",
    ].join("\n");
  }

  return [
    header,
    `export const databaseColumns: Record<string, readonly ColumnInfo[]> = {`,
    entries.map(renderColumnsEntry).join("\n"),
    `} as const;`,
    "",
    "registerDatabaseColumns(databaseColumns);",
    "",
  ].join("\n");
}

function renderColumnsEntry(entry: RegistryEntry): string {
  const columns = entry.columns
    .map(
      (col) => `    {
      name: ${JSON.stringify(col.name)},
      type: ${JSON.stringify(col.type)},
      nullable: ${String(col.nullable)},
      primaryKey: ${String(col.primaryKey)},
      hasDefault: ${String(col.hasDefault)},
      generated: ${String(col.generated)},
    },`,
    )
    .join("\n");
  return `  ${safeObjectKey(entry.entity)}: [
${columns}
  ],`;
}

function safeObjectKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/** Always emit a valid module — keeps `tsc --noEmit` happy when the schema is empty. */
function renderDeclaration(entries: RegistryEntry[]): string {
  const header = [
    "// Auto-generated by AppKit — DO NOT EDIT",
    "// Generated from config/database/schema.ts",
    "",
  ].join("\n");

  if (entries.length === 0) {
    return `${header}export {};\n`;
  }

  const body = entries.map(renderEntry).join("\n");
  return [
    header,
    'import "@databricks/appkit-ui/js";',
    "",
    'declare module "@databricks/appkit-ui/js" {',
    "  interface DatabaseRegistry {",
    body,
    "  }",
    "}",
    "",
  ].join("\n");
}

function renderEntry(entry: RegistryEntry): string {
  return `    ${entry.entity}: {
      row: ${entry.row};
      insert: ${entry.insert};
      update: ${entry.update};
      filters: ${entry.filters};
      includes: ${entry.includes};
    };`;
}

async function writeOutput(outFile: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, content, "utf8");
}

/** Match the serving generator's log cadence. */
function printLog(
  status: "HIT" | "MISS",
  start: number,
  entries: RegistryEntry[],
): void {
  const tag =
    status === "HIT"
      ? `cache ${pc.bold(pc.green("HIT "))}`
      : `cache ${pc.bold(pc.yellow("MISS"))}`;
  const elapsed = ((performance.now() - start) / 1000).toFixed(2);
  const lines: string[] = [
    "",
    `  ${pc.bold("Typegen Database")} ${pc.dim(`(${entries.length})`)}`,
    `  ${pc.dim("─".repeat(50))}`,
  ];
  if (entries.length === 0) {
    lines.push(
      `  ${tag}  ${pc.dim(status === "HIT" ? "(no change)" : "(no entities)")}`,
    );
  } else {
    for (const e of entries) lines.push(`  ${tag}  ${e.entity}`);
  }
  lines.push(`  ${pc.dim("─".repeat(50))}`);
  lines.push(`  ${pc.dim(`${elapsed}s`)}`);
  lines.push("");
  for (const line of lines) console.log(line);
}
