import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import pc from "picocolors";
import { createLogger } from "../../logging/logger";
import {
  CACHE_VERSION,
  type DatabaseCache,
  hashSchemaSourceWithDeps,
  loadDatabaseCache,
  saveDatabaseCache,
} from "./cache";
import { type RegistryEntry, walkSchema } from "./walk-schema";

const logger = createLogger("type-generator:database");

/** Path (relative to the project root) of the user's declarative schema file. */
export const SCHEMA_REL = "config/database/schema.ts";
/** Default emit target — matches the analytics/serving convention. */
export const DATABASE_TYPES_FILE = "shared/appkit-types/database.d.ts";

/**
 * Pluggable schema loader. The Vite plugin wires `server.ssrLoadModule` so the
 * schema is evaluated in Vite's own Node context (no child spawn, no tsx cold
 * start). Standalone CLIs fall through to the default `import()` loader, which
 * picks up TS source via the parent process's `tsx` loader. Tests inject a
 * fake to avoid touching the filesystem or a live Vite server.
 */
export type SchemaLoader = (
  schemaPath: string,
) => Promise<{ default: unknown }>;

const defaultLoader: SchemaLoader = (schemaPath) =>
  import(pathToFileURL(schemaPath).href) as Promise<{ default: unknown }>;

export interface GenerateDatabaseTypesOptions {
  /** Absolute path to the `.d.ts` output file. */
  outFile: string;
  /** Project root — the directory that contains `config/database/schema.ts`. */
  projectRoot: string;
  /**
   * Override the schema module loader. When omitted, uses `import()` with a
   * `file://` URL; Vite passes `ssrLoadModule`; tests pass a fake.
   */
  loadModule?: SchemaLoader;
  /** When true, bypass the cache in both directions (read and write). */
  noCache?: boolean;
}

/**
 * Read `config/database/schema.ts`, walk it, and emit the registry
 * augmentation to the configured output file. Silently returns when the
 * schema file does not exist — apps that don't use the database plugin pay
 * nothing.
 *
 * The algorithm:
 *
 * 1. Read the schema source from disk (plain text — we hash it, not the AST).
 * 2. On cache hit, re-emit the cached output and return early.
 * 3. Otherwise call the module loader to get the live `Schema` object.
 * 4. Walk the schema into flat `RegistryEntry`s (row/insert/update/filters/includes).
 * 5. Render the `declare module` block and write it.
 * 6. Update the cache with the new hash+output.
 */
export async function generateDatabaseTypes(
  options: GenerateDatabaseTypesOptions,
): Promise<void> {
  const schemaPath = path.join(options.projectRoot, SCHEMA_REL);
  const loadModule = options.loadModule ?? defaultLoader;
  const start = performance.now();

  try {
    await fs.access(schemaPath);
  } catch {
    logger.debug(
      "No schema.ts at %s; skipping database type generation",
      schemaPath,
    );
    return;
  }

  // Hash the entire reachable graph (schema.ts + every relative import). A
  // refactor that splits the schema into `./tables/*.ts` no longer fools the
  // cache into returning stale `.d.ts` output.
  const hash = await hashSchemaSourceWithDeps(schemaPath);
  const cache = options.noCache
    ? { version: CACHE_VERSION }
    : await loadDatabaseCache(options.projectRoot);

  if (!options.noCache && cache.entry?.hash === hash) {
    await writeOutput(options.outFile, cache.entry.output);
    printLog("HIT", start, []);
    return;
  }

  const mod = await loadModule(schemaPath);
  if (!mod || typeof mod !== "object" || !("default" in mod)) {
    throw new Error(
      `schema.ts at ${schemaPath} has no default export. Use 'export default defineSchema(...)'.`,
    );
  }

  const entries = walkSchema(mod.default);
  const output = renderDeclaration(entries);
  await writeOutput(options.outFile, output);

  if (!options.noCache) {
    const next: DatabaseCache = {
      version: CACHE_VERSION,
      entry: { hash, output },
    };
    await saveDatabaseCache(options.projectRoot, next);
  }

  printLog("MISS", start, entries);
}

/**
 * Compose the full `.d.ts` output. When there are no entities we still emit a
 * valid module so downstream `tsc --noEmit` runs stay happy; the file acts as
 * a stable anchor so future regenerations can replace it atomically.
 */
function renderDeclaration(entries: RegistryEntry[]): string {
  const header = [
    "// Auto-generated by AppKit — DO NOT EDIT",
    "// Generated from config/database/schema.ts",
    "",
  ].join("\n");

  if (entries.length === 0) {
    return `${header}export {};\n`;
  }

  const body = entries.map(renderEntry).join("\n");
  return [
    header,
    'import "@databricks/appkit-ui/js";',
    "",
    'declare module "@databricks/appkit-ui/js" {',
    "  interface DatabaseRegistry {",
    body,
    "  }",
    "}",
    "",
  ].join("\n");
}

function renderEntry(entry: RegistryEntry): string {
  return `    ${entry.entity}: {
      row: ${entry.row};
      insert: ${entry.insert};
      update: ${entry.update};
      filters: ${entry.filters};
      includes: ${entry.includes};
    };`;
}

async function writeOutput(outFile: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, content, "utf8");
}

/**
 * Human-readable log — matches the serving generator's cadence so both
 * typegen passes look the same in a dev terminal.
 */
function printLog(
  status: "HIT" | "MISS",
  start: number,
  entries: RegistryEntry[],
): void {
  const tag =
    status === "HIT"
      ? `cache ${pc.bold(pc.green("HIT "))}`
      : `cache ${pc.bold(pc.yellow("MISS"))}`;
  const elapsed = ((performance.now() - start) / 1000).toFixed(2);
  const lines: string[] = [
    "",
    `  ${pc.bold("Typegen Database")} ${pc.dim(`(${entries.length})`)}`,
    `  ${pc.dim("─".repeat(50))}`,
  ];
  if (entries.length === 0) {
    lines.push(
      `  ${tag}  ${pc.dim(status === "HIT" ? "(no change)" : "(no entities)")}`,
    );
  } else {
    for (const e of entries) lines.push(`  ${tag}  ${e.entity}`);
  }
  lines.push(`  ${pc.dim("─".repeat(50))}`);
  lines.push(`  ${pc.dim(`${elapsed}s`)}`);
  lines.push("");
  for (const line of lines) console.log(line);
}
