import { mapPostgresType } from "./type-map";
import type {
  IntrospectedColumn,
  IntrospectedTable,
  IntrospectionResult,
} from "./types";

const HEADER = `// AUTO-GENERATED by \`appkit db introspect\`. Review before committing.
import { defineSchema, bigint, boolean, fk, id, integer, jsonb, text, timestamp, uuid, varchar } from "@databricks/appkit";

export default defineSchema(({ table }) => {
`;

/**
 * Renders a live database snapshot into a `defineSchema()` module.
 *
 * The renderer intentionally emits one Postgres schema per file because
 * `defineSchema()` currently has one `schemaName` option. The schema is derived
 * from the tables actually returned by introspection, not from the requested
 * schema list, because the default request can include both `app` and `public`.
 */
export function renderSchema(result: IntrospectionResult): string {
  const schemaName = resolveSchemaName(result);
  const tables = sortTablesByDependencies(result.tables);
  const lines: string[] = [];
  const variables: string[] = [];
  const renderedTables = new Set<string>();

  for (const table of tables) {
    const varName = toIdentifier(toCamelCase(table.name));
    variables.push(varName);
    lines.push(renderTable(varName, table, renderedTables));
    renderedTables.add(table.name);
    if (table.policies.length) lines.push(renderPolicies(table));
  }

  return `${HEADER}${lines.join("\n\n")}\n${renderFooter(
    variables,
    schemaName,
  )}`;
}

function renderFooter(variables: string[], schemaName: string): string {
  const options =
    schemaName !== "app"
      ? `, { schemaName: ${JSON.stringify(schemaName)} }`
      : "";
  return `  return { ${variables.join(", ")} };
}${options});
`;
}

function renderTable(
  varName: string,
  table: IntrospectedTable,
  renderedTables: ReadonlySet<string>,
): string {
  const colsName = `${varName}Cols`;
  const columns = table.columns.map(
    (column) =>
      `    ${propertyKey(column.name)}: ${renderColumn(
        column,
        renderedTables,
      )},`,
  );

  return [
    `  const ${colsName} = {`,
    columns.join("\n"),
    "  };",
    `  const ${varName} = table("${table.name}", ${colsName});`,
  ].join("\n");
}

/**
 * Renders a column expression, falling back to a scalar column for self or cyclic
 * foreign keys so the generated file remains importable and visibly marks the
 * relation for manual cleanup.
 */
function renderColumn(
  column: IntrospectedColumn,
  renderedTables: ReadonlySet<string>,
): string {
  if (column.references) {
    if (!renderedTables.has(column.references.table)) {
      return `${renderScalarColumn(column)} /* TODO: foreign key to ${
        column.references.table
      }.${column.references.column} */`;
    }

    const targetTable = toIdentifier(toCamelCase(column.references.table));
    let expr = `fk(${targetTable}Cols.${propertyAccess(column.references.column)})`;
    if (
      column.references.onDelete &&
      column.references.onDelete !== "no action"
    ) {
      expr += `.onDelete("${column.references.onDelete}")`;
    }
    if (
      column.references.onUpdate &&
      column.references.onUpdate !== "no action"
    ) {
      expr += `.onUpdate("${column.references.onUpdate}")`;
    }
    if (!column.nullable) expr += ".notNull()";
    return expr;
  }

  return renderScalarColumn(column);
}

function renderScalarColumn(column: IntrospectedColumn): string {
  const mapped = mapPostgresType(column.pgType, {
    serverGenerated: column.serverGenerated,
    isPrimaryKey: column.isPrimaryKey,
  });
  if (mapped.isIdShortcut) return mapped.helper;

  let expr = mapped.helper;
  if (!column.nullable) expr += ".notNull()";
  if (column.isPrimaryKey) expr += ".primaryKey()";
  if (
    column.hasDefault &&
    !column.serverGenerated &&
    column.defaultExpression
  ) {
    expr += renderDefault(column.defaultExpression);
  }
  return expr;
}

function renderDefault(expression: string): string {
  if (expression === "now()") return ".defaultNow()";
  if (expression.startsWith("'") && expression.includes("'::")) {
    const literal = expression.slice(1, expression.indexOf("'::"));
    return `.default(${JSON.stringify(literal)})`;
  }
  return ` /* TODO: default ${expression} */`;
}

function renderPolicies(table: IntrospectedTable): string {
  return table.policies
    .map(
      (policy) =>
        `  // TODO: policy "${policy.name}" on ${table.name} (for: ${policy.for.join(", ")})`,
    )
    .join("\n");
}

/**
 * Orders referenced tables before dependent tables so generated `fk(userCols.id)`
 * expressions point at initialized column objects.
 */
function sortTablesByDependencies(
  tables: IntrospectedTable[],
): IntrospectedTable[] {
  const byName = new Map(tables.map((table) => [table.name, table]));
  const visited = new Set<string>();
  const visiting = new Set<string>();
  const out: IntrospectedTable[] = [];

  function visit(table: IntrospectedTable): void {
    if (visited.has(table.name)) return;
    if (visiting.has(table.name)) {
      // Cycles cannot be topologically sorted; keep deterministic output and
      // let the generated file surface any manual cleanup that is needed.
      return;
    }

    visiting.add(table.name);
    for (const column of table.columns) {
      const target = column.references?.table;
      const targetTable = target ? byName.get(target) : undefined;
      if (targetTable) visit(targetTable);
    }
    visiting.delete(table.name);
    visited.add(table.name);
    out.push(table);
  }

  for (const table of tables) visit(table);
  return out;
}

/**
 * Resolves the single schema that can be represented by `defineSchema()`.
 *
 * Mixed-schema output would map at least one table to the wrong schema, so the
 * renderer fails before writing misleading code.
 */
function resolveSchemaName(result: IntrospectionResult): string {
  const tableSchemas = [...new Set(result.tables.map((table) => table.schema))];
  if (tableSchemas.length > 1) {
    throw new Error(
      `Cannot render multiple database schemas (${tableSchemas.join(
        ", ",
      )}) into one defineSchema() file. Pass --schema <name> to introspect one schema.`,
    );
  }

  if (tableSchemas.length === 1) return tableSchemas[0];
  return result.schemas.length === 1 ? result.schemas[0] : "app";
}

function propertyKey(value: string): string {
  return isIdentifier(value) ? value : JSON.stringify(value);
}

function propertyAccess(value: string): string {
  return isIdentifier(value) ? value : `[${JSON.stringify(value)}]`;
}

function toCamelCase(value: string): string {
  return value.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function toIdentifier(value: string): string {
  const normalized = value.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[a-zA-Z_$]/.test(normalized) ? normalized : `table_${normalized}`;
}

function isIdentifier(value: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(value);
}
